# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53929d389de6ef5700b53cc272edb9d646ae0cc04a5195e6ecdcfbaf691eadcf2f5a232b687d880e430c8ffc8ea0c69f6a9bb7fd4d29c0ae297799ec170af55b

test:
  secret_key_base: 43cfbb9ccee769d0f866b9973b44dff84addbe87c2e72af59cfe7d153ed3c52edb9024ba18633bb293ce067609f55244baa4935b85767d64e645bf4d127dd7e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
